name: Build docs website and deploy on gh-pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2
        with:
          path: './'
      # - name: Clean npm cache directory
      #  run: npm cache clear --force
      - name: Detect yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Set up workflow caching of yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Setup git creds
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true,
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish changes
        run: |
          yarn deploy
